# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "sXn3UdItij/pUJF2zX7HKfMQIfoySv6cKdqMFquNaZOsAcMxcyg4wojTif+J+s3/ZSavRNvoMGy9vdf/1KA0/e9wEVqaAJr6QaBH8sxJdWmX4dPiab80iu6gh3ajUBivUHbyDv+AMOg5paIAUopyexQYOZPTxed3Rzpy1DS2i1JXkXcO0AIuy09t3HDyiuM0B2gD9iszemP5l1IeTxAbKU+dvGFe8w18ROLUAhAJ0iNLWTRRaCrNDLEijqlIwl1iINrQQUtZWOzlmHAljK2eJEEHr58xp2JX84gWn9g0niqj5SN4ovGS7P4VXyvSALkbY/EInDkAeqX8X8VkE6VZuKVWJ868+BnRqp0crKq3aZPyJkfqFzOOo0xAGKVx0CU7J+vPxFXPdzPMAewcY51Y3g7sjGswY/+09F9j14hgmjvBVbY5t5I34b3lTkU+WNLAlmuhS8KNsjglKyMydb553ttBA1XVkFhjbSjOPuf57Q8HU+4gsLEYqafIfjkr0jZ1P6kZw5kTv0+alPNw0KD++Yvahm699vi46smNzoC3g0MEwjdVR7ruNWzK5bDOKY/KCBGCbn0k/6P7G1Gh5P2bC722aNpBY5GLzrS6qf9+59CBZ9fas5qlW/+IaW+Jpt+Lk+PFEEVKYGxcMvuJSsWjSbE9625yDHzS5lP5heBErF4="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_python3.6 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_python3.7 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_python3.8 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi